core/urls.py
from django.urls import path, re_path
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('support/', views.support, name='support'),
    path('up/', views.upload, name='upload'),
    path('login/', views.login_, name='login'),
    path('login/submit', views.login_submit, name='login_submit'),
    path('logout/', views.logout_, name='logout'),
    path('contato', views.contato, name='contato')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import os

class Certificate(models.Model):

    name = models.CharField('Certificado', max_length=100)
    image = models.ImageField('imagem', upload_to='certificado')

    def __str__(self):
        return self.name

    def filename(self):
        return os.path.basename(self.image.name)

    class Meta:
        db_table = 'images'

class FormInformation(models.Model):

    event = models.CharField('Nome do Evento', max_length=100, blank=True)
    date = models.DateField('Data do Evento', blank=True)
    body = models.TextField('Corpo', blank=True)
    date_creaded = models.DateField(auto_now=True)
    plan = models.FileField('Filecsv',upload_to='planilhas', blank=True)

    def __str__(self):
        return self.event

    class Meta:
        db_table = 'Eventos'

core/forms.py
from django import forms
from .models import FormInformation
from.models import Certificate

class FormPreview(forms.ModelForm):
    plan = forms.FileField(
        required = False
    )
    class Meta:
        model = FormInformation
        fields = ['event', 'date', 'body', 'plan']

class Imageform(forms.ModelForm):
    name = forms.ModelChoiceField(Certificate.objects.all(), 
    widget=forms.Select,
    required=False,
    label='Selecione o Certificado'
    )

    class Meta:
        model = Certificate
        fields = ['name']


core/views.py
from django.conf import settings
from django.shortcuts import render, redirect , HttpResponseRedirect
from .forms import FormPreview
from .forms import Imageform
from .models import Certificate
from .models import FormInformation
from .apps import CreateCertificate
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import os
import csv

POST = 10

@login_required(login_url='/login/')
def index(request):
    global POST
    model = FormPreview(request.POST or None)
    cert = Imageform(request.POST or None)
    if request.method == 'POST':
        system = request.POST.get('system')
        if system == 'Preview':
            id = request.POST.get('name')
            if id == None or id == '':
                return redirect('core:index')
            POST = request.POST
            evento = request.POST.get('event')
            data = request.POST.get('date')
            body = request.POST.get('body')
            image = Certificate.objects.get(id=id)
            obj = CreateCertificate()
            obj.PreviewCretificate(str(image.image), data, evento, body)
            return redirect('core:index')
        if system == 'Finalizar':
            try:
                form = FormPreview(POST, request.FILES)
                if os.path.isfile(os.path.join(settings.MEDIA_STATIC, 'certificado.png')):
                    form.save()
                    with open(os.path.join(settings.MEDIA_ROOT,'planilhas' ,str(request.FILES['plan']))) as csvfile:
                        spamreader = csv.reader(csvfile, delimiter=',')
                        for row in spamreader:
                            obj = CreateCertificate()
                            obj.SendEmail(row[0],row[1])
                        obj.remove()
            except:
                return render(request, 'erro.html')

            return redirect('core:upload')

        else:
            return render(request, 'index.html', {
            'cert': cert,
            'model': model,
            })
    else:
            return render(request, 'index.html', {
            'cert': cert,
            'model': model,
            })
   
@login_required(login_url='/login/')        
def support(request):
    return render(request, 'support.html')

@login_required(login_url='/login/')
def upload(request):
    form = FormInformation.objects.all()
    return render(request, 'upload_file.html', {
        'form':form
    })
    
def login_(request):
    return render(request, 'login.html')

@csrf_protect
def login_submit(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:index')
        else:
            messages.error(request, 'Usuário ou senha inválido. Por favor tentar novamente ou entrar em contato com administrador')
    return redirect('core:login')

    
def logout_(request):
    obj = CreateCertificate()
    obj.remove()
    logout(request)
    response = HttpResponseRedirect('/login/')
    response.delete_cookie('username')
    return redirect('core:login')


@login_required(login_url='/login/')        
def contato(request):
    return render(request, 'contato.html')

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>Document</title>
</head>
<body>
    <header>
        <div class="container">
            <p class="text-right">...</p>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:support' %}">Support</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:contato' %}">Contatos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:logout' %}">Sair</a>
                </li>
              </ul>
            </div>
          </div>
        {% block content %}
        {% endblock %}
    <footer></footer>
</body>
</html>

core/templates/contato.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Support</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <p class="text-right">...</p>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:support' %}">Support</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:contato' %}">Contatos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:logout' %}">Sair</a>
                </li>
              </ul>
            </div>
          </div>
<div class="jumbotron text-center">
  <h1>Contato</h1>
  <p>mande um e-mail para</p>
  <p>fernando.almeida.pinto@gmail.com</p>
</div>
<footer>
    <div style="text-align: center; padding: 15px;">
        <strong>Criado por:</strong> Fernando Almeida
      </div>
</footer>
</body>
</html>

core/templates/erro.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <script type="text/javascript">
    // using jQuery
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    </script>
    </header>
    <main>
        <img src="{% static 'temp/certificado.png' %}" alt="">
    </main>
    <aside>
        <div class="alert alert-danger">
            <strong>Error!</strong> Houve um Problema ao enviar seus Certificados. Verifique o formato de sua planilha ou entre en contato com o administrador.
          </div>
    </aside>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}  
    </header>
    <main>
        <img class="image-static" src="{% static 'temp/certificado.png' %}" alt="{% static 'temp/certificado.png' %}">
        <a class='atualizaimagem'  href="{% static 'temp/certificado.png' %}"><h4>imagem</h4></a>
    </main>
    <aside>
        <div class="forms">
            <form class='main_form' enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>Certificado</th>
                        <th>{{cert.name}}</th>
                    </tr>
                    <tr>
                        <th>Evento</th>
                        <th>{{model.event}}</th>
                    </tr>
                    <tr>
                        <th>Data</th>
                        <th>{{model.date}}</th>
                    </tr>
                    <tr>
                        <th>Body</th>
                        <th>{{model.body}}</th>
                    </tr>
                </table>
                    <button id="submit_forms" type="submit" class="btn btn-primary" value="Preview" name="system">
                        Preview</button>
            </form>
        </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>Importe Planilha</th>
                    </tr>
                    <tr>
                        <th>{{model.plan}}</th>
                        <th><button id="submit_forms" type="submit" class="btn btn-success" value="Finalizar" name="system">
                            Finalizar</button>
                        </form></th>
                    </tr>
                </table>
                <div class="alert alert-warning">
                    <strong>Cuidado!</strong> Certifique-se de apenas Finalizar o seu Projeto, 
                    quando tiver certeza que seu certificado está correto.
                  </div>
                <div class="alert alert-primary">
                    <strong>Observação!</strong> Caso o Botão Preview não esteja funcionando, você pode visualizar seu certificado no botão 'imagem' logo a baixo do seu certificado e mandar atualizar
                </div>
    </aside>
{% endblock %}

core/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Certificate</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
  <h1>Certificados</h1>
  <p>Aplicação destinada a facilitar o processo de envio de certificados</p> 
</div>

    <div class="container mt-4">
        <form action="submit" method="post">{% csrf_token %}
            <h2>Login</h2>
            <div class="form-group">
                <input type="text" class="form-control" id="username" name="username"
                    placeholder="E-mail">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password" name="password"
                    placeholder="Senha">
            </div>
            {% for message in messages %}
            <div class="alert alert-danger">
                <strong>Erro!</strong> 
                {{message}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Entrar</button>
        </form>
    </div>
    
</body>
</html>

core/templates/support.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Support</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
      <div class="container">
        <p class="text-right">...</p>
        <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:support' %}">Support</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:contato' %}">Contatos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:logout' %}">Sair</a>
            </li>
          </ul>
        </div>
      </div>
<div class="jumbotron text-center">
  <h1>Importante</h1>
  <p>Segue algumas informações importantes</p> 
</div>
  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
        <h3>Formato da Planilha</h3>
        <div class="alert alert-warning">
            <strong>Importante!</strong> A planilha deve ser salva em formato .csv (separado por vírgula)
          </div>
          <img src="{% static 'image/Planilha.png' %}" alt="">
        </div>
  </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <h3>Formato das colunas</h3>
            <div class="alert alert-info">
              <strong>Info!</strong> Ao criar sua planilha, lembre-se de deve existir uma coluna para Nome (que irão para o certificado) e E-mail que serão encaminhados
            </div>
            <img src="{% static 'image/Planilha2.png' %}" alt="">
          </div>
    </div>
  </div>
<footer>
    <div style="text-align: center; padding: 15px;">
        <strong>Criado por:</strong> Fernando Almeida
      </div>
</footer>
</body>
</html>

core/templates/upload_file.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Support</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <p class="text-right">...</p>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:support' %}">Support</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:contato' %}">Contatos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:logout' %}">Sair</a>
                </li>
              </ul>
            </div>
          </div>
<div class="jumbotron text-center">
    <div class="alert alert-success">
        <strong>Success!</strong> Enviado com sucesso.
      </div>
</div>
<footer>
    <div style="text-align: center; padding: 15px;">
        <strong>Criado por:</strong> Fernando Almeida
      </div>
</footer>
</body>
</html>